providerType: OPEN_AI
# Use Magnolia Passowrds App to store OpenAI API Key and add node path here
apiKey: "/magnolia-lean-ai-toolkit/openai_api_key"
modelName: "gpt-5.6-terra"
logRequests: true
logResponses: true